### ISSUE TITLE
Kill or restart?

### ISSUE THREAD

**Issue by randy-girard** [klaxit/sidekiq-worker-killer#11]
Sorry if this is obvious, but does this kill and not start the worker back up, or will it do a restart. Thanks

**Comment by msxavi** [comment]
Hi @randy-girard 

It doesn't restart, you may have to do it manually or have a monitor tool like [upstart](http://upstart.ubuntu.com/) or [monit](https://mmonit.com/monit/) to restart Sidekiq automatically.

**Comment by BuonOmo** [comment]
@randy-girard if you are using Heroku, restarts are automated as well :)

I don't think we could handle a _restart_ since the process is kind of killing itself: we are generating a child thread from sidekiq process, and it is this thread that sends SIGTERM, and then dies as well...

**Comment by randy-girard** [comment]
Thanks yall.
