### ISSUE TITLE
Add `on_shutdown` hook

### ISSUE THREAD

**Issue by jacobobq** [klaxit/sidekiq-worker-killer#22]
This is a proposal to add another hook that is simply called whenever a shutdown finally happens. This would give the client the chance to customize any actions taken before shutdown like logging to custom services or incrementing a Redis counter to ban processes that consistently step out of their quota (this are exactly my real-life usecases, but probably there are more.)

Currently, the library supports the `skip_shutdown_if` callback to prevent unwanted shutdowns. We plan on using the `skip_shutdown_if` to implement this actions, but this is semantically troublesome and causes a bad separation of concerns, thus the need for an independent `on_shutdown` callback.

We could also proceed to implement the current logging message through this facility as the default option, so it's possible for the user to completely override it if desired.

Option | Defaults | Description
-- | -- | --
on_shutdown | proc {void} | Executes a block of code when the shutdown has been requested.

I'd be willing to write a PR myself if this is something that you consider fits with the gem's intent.

**Comment by ccyrille** [comment]
Hi @jacobobq, sorry for the late reply. This makes sense and we would be ok to integrate it! If you are willing to submit a PR on this, I will review it shortly.

**Comment by jacobobq** [comment]
Yes. I'll send a PR ASAP.
