### ISSUE TITLE
Worker killer does not honor grace period

### ISSUE THREAD

**Issue by VindictivePotato** [klaxit/sidekiq-worker-killer#7]
I've been using the newest version of this gem (6eb0dc3d4ba1d06b1eea387e044e5fdc14aa904e) to try out the new options introduced in 955cfeaa11afa7834ef8b4601e73f8c8342eb7cc - especially infinite grace periods.

Right now, the grace period isn't honored at all and all currently running jobs are forcefully shut down immediately. The following log shows SIGTERM is sent right after the SIGTSTP (instead of waiting 20 seconds):
 
> 2019-05-22T11:28:53.240Z 3376 TID-gqukurqkw MyJob JID-69c524c868805f8ec3229f1a INFO: start
> 2019-05-22T11:31:20.067Z 3376 TID-gqukurqkw MyJob JID-69c524c868805f8ec3229f1a WARN: current RSS 806.83984375 of my.host:3376 exceeds maximum RSS 512
> 2019-05-22T11:31:20.077Z 3376 TID-gqukurqkw MyJob JID-69c524c868805f8ec3229f1a INFO: done: 146.838 sec
> 2019-05-22T11:31:20.078Z 3376 TID-gqukic4eg WARN: sending TSTP to my.host:3376
> 2019-05-22T11:31:20.078Z 3376 TID-gqukic4eg WARN: shutting down my.host:3376 in 20 seconds
> 2019-05-22T11:31:20.079Z 3376 TID-gqukey6oo INFO: Received TSTP, no longer accepting new work
> 2019-05-22T11:31:20.080Z 3376 TID-gqukic4eg WARN: sending SIGTERM to my.host:3376
> 2019-05-22T11:31:20.080Z 3376 TID-gqukic4eg WARN: waiting 30 seconds before sending SIGKILL to my.host:3376
> 2019-05-22T11:31:20.080Z 3376 TID-gqukurz8o INFO: Scheduler exiting...
> 2019-05-22T11:31:20.081Z 3376 TID-gqukey6oo INFO: Terminating quiet workers
> 2019-05-22T11:31:20.081Z 3376 TID-gqukurpww INFO: Scheduler exiting...
> 2019-05-22T11:31:20.081Z 3376 TID-gqukey6oo INFO: Shutting down
> 2019-05-22T11:31:20.582Z 3376 TID-gqukey6oo INFO: Pausing to allow workers to finish...
> 2019-05-22T11:31:22.586Z 3376 TID-gqukey6oo INFO: Bye!

I've tracked that bug down to this method:

https://github.com/klaxit/sidekiq-worker-killer/blob/6eb0dc3d4ba1d06b1eea387e044e5fdc14aa904e/lib/sidekiq/worker_killer.rb#L62-L69

`no_jobs_on_quiet_processes?` is always true.
This is because there are two implementations of that method, with the second overwriting the first:

https://github.com/klaxit/sidekiq-worker-killer/blob/6eb0dc3d4ba1d06b1eea387e044e5fdc14aa904e/lib/sidekiq/worker_killer.rb#L77-L82

https://github.com/klaxit/sidekiq-worker-killer/blob/6eb0dc3d4ba1d06b1eea387e044e5fdc14aa904e/lib/sidekiq/worker_killer.rb#L84-L89

The second implementation will always return true because `!process["busy"] == 0` is always false (missing parentheses).

The duplicate method was introduced in https://github.com/klaxit/sidekiq-worker-killer/commit/e06864f16f91b6c2a1b2914aae009f50a039208e. Removing the second implementation should fix this issue.

By the way: The property `process["quiet"] ` always returns a string (at least on Sidekiq 5.2.7 it returns either `"true"` or `"false"`), so the second condition is always true.

**Comment by BuonOmo** [comment]
Thank you for this very clearly explained issue 😄

 I just verified, and our Sidekiq returns indeed a string for the property `process["quiet"]`.

The second issue you spotted must have been a slippery edit when we changed [our Rubocop rules](/klaxit/ruby) to refuse `.zero?` writing. I'd go for something like:

```ruby
 def no_jobs_on_quiet_processes? 
   Sidekiq::ProcessSet.new.each do |process| 
     return false if process["busy"] != 0 && process["quiet"] == "true"
   end 
   true 
 end 
 ```


Since you've investigated so far, would you like to add your contribution with a Pull Request? If not I'll open one myself (maybe next week) and ping you then.
